# Generated by Django 3.1.6 on 2021-03-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyer_status',
            field=models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Decline', 'Decline'), ('Reject', 'Reject'), ('Drop', 'Drop')], default='Register', max_length=100),
        ),
    ]
