# Generated by Django 3.1.4 on 2021-03-26 10:48

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20210306_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='is_decline',
        ),
        migrations.AddField(
            model_name='buyer',
            name='aadhaar_card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='banking_passbook',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='contact_person_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='gst_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pan_card',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='selling_product',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='cancelled_ca_cheque',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='drug_licence',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='fssai_docs',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='gstin_docs',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='scale_licence',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='trade_licence',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='udhyaam',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
    ]
