# Generated by Django 3.1.4 on 2021-05-11 07:18

from django.db import migrations, models
import django_base64field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_auto_20210326_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='banking_passbook',
            new_name='aadhaar_docs',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='cancelled_ca_cheque',
            new_name='cancelled_cheque_docs',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='scale_licence',
            new_name='drug_docs',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='drug_licence',
            new_name='pan_docs',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='trade_licence',
            new_name='scale_docs',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='udhyaam',
            new_name='trade_docs',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='selling_product',
        ),
        migrations.AddField(
            model_name='buyer',
            name='org_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='udhyaam_docs',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='aadhaar_card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_status',
            field=models.CharField(blank=True, choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Decline', 'Decline'), ('Draf', 'Draf'), ('Drop', 'Drop')], default='Register', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
