# Generated by Django 3.1.4 on 2021-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20210512_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_status',
            field=models.CharField(blank=True, choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Decline', 'Decline'), ('Draft', 'Draft'), ('Drop', 'Drop')], default='Register', max_length=100, null=True),
        ),
    ]
