# Generated by Django 3.1.4 on 2021-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_auto_20210514_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Decline', 'Decline'), ('Draft', 'Draft'), ('Drop', 'Drop')], default='Pending', max_length=100, null=True),
        ),
    ]
