# Generated by Django 3.1.4 on 2021-06-04 21:08

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_auto_20210602_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='address_2',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='aadhaar_docs',
            new_name='cancelled_cheque',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='contact_person_name',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='cancelled_cheque_docs',
            new_name='drug_license',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='drug_docs',
            new_name='fssai_license',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='fssai_docs',
            new_name='gst_certificate',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='gstin_docs',
            new_name='scale_licence',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='pan_docs',
            new_name='trade_license',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='scale_docs',
            new_name='udhyaam_certificate',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='trade_docs',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='udhyaam_docs',
        ),
        migrations.AddField(
            model_name='buyer',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='cluster',
            field=models.CharField(blank=True, choices=[('South', 'South'), ('North', 'North'), ('East', 'East'), ('West', 'West')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='drug_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='fssai_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='scale_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='trade_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='udhyaam_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='aadhaar_card',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Draft', 'Draft')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pan_card',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pin_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
