# Generated by Django 3.1.4 on 2021-06-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_auto_20210604_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='drug_number',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='fssai_number',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='scale_number',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='trade_number',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='udhyaam_number',
        ),
    ]
