# Generated by Django 3.1.4 on 2021-06-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_delete_cart'),
        ('buyer', '0012_auto_20210604_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
