# Generated by Django 3.1.4 on 2021-06-04 22:11

from django.db import migrations, models
import django_base64field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0013_delete_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('buyer_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Draft', 'Draft')], default='Pending', max_length=100, null=True)),
                ('owner_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('pin_code', models.CharField(max_length=6, null=True)),
                ('mobile_number', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_certificate', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('fssai_license', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('udhyaam_certificate', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('drug_license', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('trade_license', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('scale_licence', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('cancelled_cheque', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.CharField(blank=True, choices=[('South', 'South'), ('North', 'North'), ('East', 'East'), ('West', 'West')], max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyer',
            },
        ),
    ]
