# Generated by Django 3.1.4 on 2021-06-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0015_buyer_buyer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='cancelled_cheque',
        ),
    ]
