# Generated by Django 3.1.4 on 2021-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0016_remove_buyer_cancelled_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
