# Generated by Django 3.1.6 on 2021-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_user', models.CharField(choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=100)),
                ('user_id', models.IntegerField()),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
            ],
        ),
    ]
