# Generated by Django 3.1.6 on 2021-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_key',
            field=models.TextField(null=True),
        ),
    ]
