# Generated by Django 3.1.6 on 2021-03-05 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210305_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 16, 29, 51, 523536, tzinfo=utc)),
        ),
    ]
