# Generated by Django 3.1.6 on 2021-03-06 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210305_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('valid_till', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'LoginOtp',
                'verbose_name_plural': 'LoginOtps',
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 4, 0, 32, 104642, tzinfo=utc)),
        ),
    ]
