# Generated by Django 3.1.6 on 2021-03-06 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210306_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 4, 3, 9, 305416, tzinfo=utc)),
        ),
    ]
