# Generated by Django 3.1.6 on 2021-03-09 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210306_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 5, 54, 34, 620707, tzinfo=utc)),
        ),
    ]
