# Generated by Django 3.1.6 on 2021-03-12 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210309_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 15, 30, 19, 181395, tzinfo=utc)),
        ),
    ]
