# Generated by Django 3.1.4 on 2021-03-24 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210324_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 1, 20, 40, 834736, tzinfo=utc)),
        ),
    ]
