# Generated by Django 3.1.4 on 2021-03-24 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210324_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 12, 30, 15, 483137, tzinfo=utc)),
        ),
    ]
