# Generated by Django 3.1.4 on 2021-03-25 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210324_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 4, 56, 49, 24906, tzinfo=utc)),
        ),
    ]
