# Generated by Django 3.1.4 on 2021-03-25 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210325_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 15, 32, 12, 932489, tzinfo=utc)),
        ),
    ]
