# Generated by Django 3.1.4 on 2021-03-26 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210326_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 8, 36, 57, 371281, tzinfo=utc)),
        ),
    ]
