# Generated by Django 3.1.4 on 2021-03-27 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20210326_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 8, 2, 50, 160496, tzinfo=utc)),
        ),
    ]
