# Generated by Django 3.1.4 on 2021-03-27 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20210327_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 14, 32, 13, 291639, tzinfo=utc)),
        ),
    ]
