# Generated by Django 3.1.4 on 2021-04-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20210327_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
