# Generated by Django 3.1.4 on 2021-05-29 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210528_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_otp',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='email_otp',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 13, 32, 4, 483059)),
        ),
        migrations.AlterField(
            model_name='loginotp',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 13, 32, 4, 467437)),
        ),
    ]
