# Generated by Django 3.1.4 on 2021-05-29 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20210529_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_otp',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 11, 7, 712904)),
        ),
        migrations.AlterField(
            model_name='loginotp',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 11, 7, 712904)),
        ),
    ]
