# Generated by Django 3.1.4 on 2021-03-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210325_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
