# Generated by Django 3.1.4 on 2021-03-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_xproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xproduct',
            name='product_image',
            field=models.TextField(null=True),
        ),
    ]
