# Generated by Django 3.1.4 on 2021-03-26 04:51

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210326_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xproduct',
            name='product_image',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True),
        ),
    ]
