# Generated by Django 3.1.4 on 2021-03-26 05:13

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210326_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Xproduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True),
        ),
    ]
