# Generated by Django 3.1.4 on 2021-03-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210326_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_per',
        ),
    ]
