# Generated by Django 3.1.4 on 2021-04-09 12:08

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210326_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
