# Generated by Django 3.1.4 on 2021-04-10 10:16

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210410_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=0)),
                ('category_name', models.CharField(max_length=200, null=True)),
                ('category_image', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999, null=True)),
            ],
        ),
    ]
