# Generated by Django 3.1.4 on 2021-04-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_product'),
        ('product', '0014_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
