# Generated by Django 3.1.4 on 2021-04-29 05:59

from django.db import migrations, models
import django.db.models.deletion
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0049_seller_banking_passbook_docs'),
        ('product', '0015_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Reject', 'Reject')], default='Pending', max_length=100, null=True)),
                ('hsn_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=100)),
                ('set_type', models.CharField(max_length=100)),
                ('set_of', models.CharField(blank=True, max_length=100)),
                ('set_specification', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('return_day', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specification_name_1', models.CharField(max_length=100)),
                ('specification_name_2', models.CharField(max_length=100)),
                ('specification_name_3', models.CharField(max_length=100)),
                ('specification_name_4', models.CharField(max_length=100)),
                ('specification_name_5', models.CharField(max_length=100)),
                ('specification_name_6', models.CharField(max_length=100)),
                ('specification_name_7', models.CharField(max_length=100)),
                ('specification_name_8', models.CharField(max_length=100)),
                ('specification_name_9', models.CharField(max_length=100)),
                ('specification_name_10', models.CharField(max_length=100)),
                ('specification_name_11', models.CharField(max_length=100)),
                ('specification_name_12', models.CharField(max_length=100)),
                ('specification_remark_1', models.CharField(max_length=100)),
                ('specification_remark_2', models.CharField(max_length=100)),
                ('specification_remark_3', models.CharField(max_length=100)),
                ('specification_remark_4', models.CharField(max_length=100)),
                ('specification_remark_5', models.CharField(max_length=100)),
                ('specification_remark_6', models.CharField(max_length=100)),
                ('specification_remark_7', models.CharField(max_length=100)),
                ('specification_remark_8', models.CharField(max_length=100)),
                ('specification_remark_9', models.CharField(max_length=100)),
                ('specification_remark_10', models.CharField(max_length=100)),
                ('specification_remark_11', models.CharField(max_length=100)),
                ('specification_remark_12', models.CharField(max_length=100)),
                ('product_photo_1', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('product_photo_2', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('product_photo_3', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('product_photo_4', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('product_photo_5', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
