# Generated by Django 3.1.4 on 2021-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210429_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventary',
            name='offline_sele_quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventary',
            name='online_sele_quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
