# Generated by Django 3.1.4 on 2021-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_inventary_inventary_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventary',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_1',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_2',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_3',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_4',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_5',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_price_1',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_price_2',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_price_3',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_price_4',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='moq_price_5',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='inventary',
            name='return_day',
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_price_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_price_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_price_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_price_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_price_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_day',
            field=models.IntegerField(null=True),
        ),
    ]
