# Generated by Django 3.1.4 on 2021-05-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210506_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Draf', 'Draf'), ('Reject', 'Reject')], default='Pending', max_length=100, null=True),
        ),
    ]
