# Generated by Django 3.1.4 on 2021-05-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0053_auto_20210503_1805'),
        ('product', '0027_auto_20210506_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventary',
            new_name='Inventory',
        ),
    ]
