# Generated by Django 3.1.4 on 2021-05-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20210507_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='offline_sele_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='online_sele_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
