# Generated by Django 3.1.4 on 2021-05-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20210507_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='offline_sele_quantity',
            new_name='offline_sell_quantity',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='online_sele_quantity',
            new_name='online_sell_quantity',
        ),
    ]
