# Generated by Django 3.1.4 on 2021-05-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20210507_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='moq_1',
            new_name='moq_end_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_2',
            new_name='moq_end_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_3',
            new_name='moq_end_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_4',
            new_name='moq_end_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_5',
            new_name='moq_start_1',
        ),
        migrations.AddField(
            model_name='product',
            name='moq_end_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_start_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_start_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_start_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_start_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
