# Generated by Django 3.1.4 on 2021-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20210510_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_1',
            new_name='moq_end_quantity_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_2',
            new_name='moq_end_quantity_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_3',
            new_name='moq_end_quantity_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_4',
            new_name='moq_end_quantity_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_5',
            new_name='moq_end_quantity_5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_start_1',
            new_name='moq_start_quantity_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_start_2',
            new_name='moq_start_quantity_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_start_3',
            new_name='moq_start_quantity_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_start_4',
            new_name='moq_start_quantity_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_start_5',
            new_name='moq_start_quantity_5',
        ),
    ]
