# Generated by Django 3.1.4 on 2021-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20210510_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.IntegerField(null=True),
        ),
    ]
