# Generated by Django 3.1.4 on 2021-05-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
