# Generated by Django 3.1.4 on 2021-05-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
    ]
