# Generated by Django 3.1.4 on 2021-05-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_cate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cate',
            new_name='Product_Rating',
        ),
    ]
