# Generated by Django 3.1.4 on 2021-05-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20210514_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_rating',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='product_rating',
            name='product',
        ),
        migrations.AddField(
            model_name='product_rating',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
