# Generated by Django 3.1.4 on 2021-05-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20210512_1342'),
        ('product', '0042_product_rating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_rating',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer'),
        ),
    ]
