# Generated by Django 3.1.4 on 2021-05-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_product_rating_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='Product_Rating',
        ),
    ]
