# Generated by Django 3.1.4 on 2021-05-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20210514_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='buyer',
            field=models.IntegerField(null=True),
        ),
    ]
