# Generated by Django 3.1.4 on 2021-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_rating_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Draft', 'Draft'), ('Reject', 'Reject')], default='Pending', max_length=100, null=True),
        ),
    ]
