# Generated by Django 3.1.4 on 2021-06-09 10:07

from django.db import migrations, models
import django.db.models.deletion
import django_base64field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0069_auto_20210603_2237'),
        ('product', '0046_auto_20210514_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_slab', models.FloatField(null=True)),
                ('slab', models.CharField(max_length=100, null=True)),
                ('return_day', models.IntegerField(null=True)),
                ('moq_1_start', models.IntegerField(null=True)),
                ('moq_1_end', models.IntegerField(null=True)),
                ('moq_1_price', models.FloatField(null=True)),
                ('moq_2_start', models.IntegerField(null=True)),
                ('moq_2_end', models.IntegerField(null=True)),
                ('moq_2_price', models.FloatField(null=True)),
                ('moq_3_start', models.IntegerField(null=True)),
                ('moq_3_end', models.IntegerField(null=True)),
                ('moq_3_price', models.FloatField(null=True)),
                ('moq_4_start', models.IntegerField(null=True)),
                ('moq_4_end', models.IntegerField(null=True)),
                ('moq_4_price', models.FloatField(null=True)),
                ('moq_5_start', models.IntegerField(null=True)),
                ('moq_5_price', models.FloatField(null=True)),
                ('moq_5_end', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_quantity_1',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_quantity_2',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_photo_1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_photo_2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_photo_3',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_photo_4',
            new_name='image_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_photo_5',
            new_name='image_5',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_quantity_3',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_end_quantity_4',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_start_quantity_1',
            new_name='set_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='moq_start_quantity_2',
            new_name='tittle',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_end_quantity_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_price_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_price_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_price_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_price_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_price_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_start_quantity_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_start_quantity_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moq_start_quantity_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='set_of',
        ),
        migrations.RemoveField(
            model_name='product',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='set_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_11',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_12',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_name_9',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_11',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_12',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification_remark_9',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='inventory',
            name='low_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='offer_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='offer_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='offer_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='offer_stock',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Set', 'Set')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='set_contains',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='pricing',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
    ]
