# Generated by Django 3.1.4 on 2021-06-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_auto_20210609_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='offer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='offer_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_1_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_1_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_2_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_2_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_2_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_3_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_3_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_3_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_4_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_4_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_4_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_5_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_5_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='moq_5_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='set_contains',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='set_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
