# Generated by Django 3.1.4 on 2021-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20210609_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Pending', max_length=100, null=True),
        ),
    ]
