# Generated by Django 3.1.4 on 2021-06-09 16:08

from django.db import migrations, models
import django.db.models.deletion
import django_base64field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0069_auto_20210603_2237'),
        ('product', '0054_auto_20210609_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Pending', max_length=100, null=True)),
                ('image_1', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('image_2', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('image_3', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('image_4', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('image_5', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('image_6', django_base64field.fields.Base64Field(blank=True, default='', max_length=9999999999999999999999999999, null=True)),
                ('specification', models.TextField(null=True)),
                ('tittle', models.TextField(null=True)),
                ('colour', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('hsn_code', models.IntegerField(null=True)),
                ('sale_type', models.CharField(choices=[('Piece', 'Piece'), ('Set', 'Set')], max_length=100, null=True)),
                ('set_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('set_contains', models.TextField(blank=True, null=True)),
                ('mrp', models.FloatField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Pending', max_length=100, null=True)),
                ('sku_id', models.TextField(default=uuid.uuid4, null=True)),
                ('gst_slab', models.FloatField(null=True)),
                ('slab', models.CharField(max_length=100, null=True)),
                ('return_day', models.IntegerField(null=True)),
                ('moq_1_start', models.IntegerField(null=True)),
                ('moq_1_end', models.IntegerField(blank=True, null=True)),
                ('moq_1_price', models.FloatField(blank=True, null=True)),
                ('moq_2_start', models.IntegerField(blank=True, null=True)),
                ('moq_2_end', models.IntegerField(blank=True, null=True)),
                ('moq_2_price', models.FloatField(blank=True, null=True)),
                ('moq_3_start', models.IntegerField(blank=True, null=True)),
                ('moq_3_end', models.IntegerField(blank=True, null=True)),
                ('moq_3_price', models.FloatField(blank=True, null=True)),
                ('moq_4_start', models.IntegerField(blank=True, null=True)),
                ('moq_4_end', models.IntegerField(blank=True, null=True)),
                ('moq_4_price', models.FloatField(blank=True, null=True)),
                ('moq_5_start', models.IntegerField(blank=True, null=True)),
                ('moq_5_price', models.FloatField(blank=True, null=True)),
                ('moq_5_end', models.IntegerField(blank=True, null=True)),
                ('offer_stock', models.BooleanField(default=False, null=True)),
                ('offer_start_date', models.DateField(blank=True, null=True)),
                ('offer_end_date', models.DateField(blank=True, null=True)),
                ('offer_details', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Pending', max_length=100, null=True)),
                ('total_quantity', models.IntegerField(null=True)),
                ('low_stock', models.IntegerField(null=True)),
                ('offline_sell_quantity', models.IntegerField(default=0, null=True)),
                ('online_sell_quantity', models.IntegerField(default=0, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
