# Generated by Django 3.1.4 on 2021-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_inventory_pricing_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='out_of_stock',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
