# Generated by Django 3.1.6 on 2021-02-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('gstin', models.ImageField(null=True, upload_to='media')),
                ('gstin_docs', models.ImageField(upload_to='media')),
                ('fssai_docs', models.ImageField(upload_to='media')),
                ('udhyaam', models.ImageField(upload_to='media')),
                ('drug_licence', models.ImageField(upload_to='media')),
                ('trade_licence', models.ImageField(upload_to='media')),
                ('scale_licence', models.ImageField(upload_to='media')),
                ('cancelled_ca_cheque', models.ImageField(upload_to='media')),
                ('mobile_number', models.CharField(max_length=10)),
                ('email_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
