# Generated by Django 3.1.6 on 2021-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='gstin',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='gstin',
            field=models.ImageField(upload_to='media'),
        ),
    ]
