# Generated by Django 3.1.6 on 2021-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20210216_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
