# Generated by Django 3.1.6 on 2021-02-19 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20210218_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='aadhaar_card',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='seller',
            name='banking_details',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='seller',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='org_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='seller',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='seller',
            name='ref_application_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='selling_product',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller_register',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller_register',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller_register',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller_register',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
