# Generated by Django 3.1.6 on 2021-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20210219_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_register',
            name='profile_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
