# Generated by Django 3.1.6 on 2021-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20210219_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='aadhaar_card',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='seller',
            name='banking_details',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact_person_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pan_card',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ref_application_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='selling_product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='aadhaar_card',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='banking_details',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='contact_person_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='gst_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='pan_card',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='ref_application_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seller_register',
            name='selling_product',
            field=models.TextField(),
        ),
    ]
