# Generated by Django 3.1.6 on 2021-02-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20210219_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
                ('added_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=999999999)),
                ('discount_per', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media')),
                ('product_tittle', models.TextField()),
                ('brand_name', models.TextField()),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
