# Generated by Django 3.1.6 on 2021-02-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.ImageField(upload_to='media')),
                ('fssai_docs', models.ImageField(upload_to='media')),
                ('udhyaam', models.ImageField(upload_to='media')),
                ('drug_licence', models.ImageField(upload_to='media')),
                ('trade_licence', models.ImageField(upload_to='media')),
                ('cancelled_ca_cheque', models.ImageField(upload_to='media')),
                ('shop_establishment_certificate', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
