# Generated by Django 3.1.6 on 2021-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_loginotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller_Register',
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Decline', 'Decline'), ('Drop', 'Drop')], default='Register', max_length=100),
        ),
    ]
