# Generated by Django 3.1.6 on 2021-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_auto_20210305_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Decline', 'Decline'), ('Reject', 'Reject'), ('Drop', 'Drop')], default='Register', max_length=100),
        ),
    ]
