# Generated by Django 3.1.6 on 2021-03-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20210305_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOtp',
        ),
    ]
