# Generated by Django 3.1.6 on 2021-03-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_auto_20210306_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='GST_commission',
            field=models.DecimalField(decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='TCS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='gross_commission',
            field=models.DecimalField(decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='net_commission',
            field=models.DecimalField(decimal_places=2, max_digits=999999999, null=True),
        ),
    ]
