# Generated by Django 3.1.6 on 2021-03-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0020_auto_20210306_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Verified', 'Verified'), ('Draf', 'Draf'), ('Drop', 'Drop')], default='Register', max_length=100),
        ),
    ]
