# Generated by Django 3.1.6 on 2021-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0022_auto_20210312_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='type_of_seller',
            field=models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Verified', 'Verified'), ('Draf', 'Draf'), ('Drop', 'Drop')], default='Register', max_length=100),
        ),
    ]
