# Generated by Django 3.1.4 on 2021-03-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0023_seller_type_of_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='banking_details',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cancelled_ca_cheque',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='drug_licence',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='fssai_docs',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gstin_docs',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='scale_licence',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='trade_licence',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='udhyaam',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
