# Generated by Django 3.1.4 on 2021-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0025_auto_20210323_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
