# Generated by Django 3.1.4 on 2021-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0026_auto_20210323_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='gstin_docs',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
