# Generated by Django 3.1.4 on 2021-03-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0027_seller_gstin_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='gstin_docs',
        ),
    ]
