# Generated by Django 3.1.4 on 2021-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0028_remove_seller_gstin_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='state',
        ),
        migrations.AddField(
            model_name='seller',
            name='gstin_docs',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
