# Generated by Django 3.1.4 on 2021-03-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0029_auto_20210323_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='gstin_docs',
        ),
        migrations.AddField(
            model_name='seller',
            name='address_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
