# Generated by Django 3.1.4 on 2021-03-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0030_auto_20210323_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
