# Generated by Django 3.1.4 on 2021-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0032_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
