# Generated by Django 3.1.4 on 2021-03-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0033_auto_20210324_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
