# Generated by Django 3.1.4 on 2021-03-24 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0034_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address_1', models.CharField(max_length=100, null=True)),
                ('address_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('mobile_number', models.CharField(max_length=12, null=True)),
                ('email_address', models.CharField(max_length=100)),
                ('org_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('selling_product', models.TextField(null=True)),
                ('seller_status', models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Verified', 'Verified'), ('Draf', 'Draf'), ('Drop', 'Drop')], default='Register', max_length=100, null=True)),
                ('gst_number', models.CharField(max_length=100, null=True)),
                ('contact_person_name', models.CharField(max_length=100, null=True)),
                ('pan_card', models.CharField(max_length=10, null=True)),
                ('aadhaar_card', models.CharField(max_length=16, null=True)),
                ('type_of_seller', models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Verified', 'Verified'), ('Draf', 'Draf'), ('Drop', 'Drop')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
