# Generated by Django 3.1.4 on 2021-03-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0035_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='type_of_seller',
        ),
    ]
