# Generated by Django 3.1.4 on 2021-03-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0038_auto_20210324_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_status',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='selling_product',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='type_of_seller',
        ),
    ]
