# Generated by Django 3.1.4 on 2021-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0040_auto_20210324_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='GST_commission',
            field=models.DecimalField(decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='TCS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='gross_commission',
            field=models.DecimalField(decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='net_commission',
            field=models.DecimalField(decimal_places=2, max_digits=999999999, null=True),
        ),
    ]
