# Generated by Django 3.1.4 on 2021-03-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0041_auto_20210324_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='GST_commission',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gross_commission',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='net_commission',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
