# Generated by Django 3.1.4 on 2021-03-27 08:02

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0043_auto_20210325_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='banking_passbook',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='cancelled_ca_cheque',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='drug_licence',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='fssai_docs',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='gstin_docs',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='scale_licence',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='trade_licence',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='udhyaam',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='GST_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='TCS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='aadhaar_card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gross_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='net_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='selling_product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='type_of_seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
