# Generated by Django 3.1.4 on 2021-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0044_auto_20210327_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='selling_product',
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='pin_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
