# Generated by Django 3.1.4 on 2021-04-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0047_auto_20210421_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='banking_passbook_docs',
        ),
    ]
