# Generated by Django 3.1.4 on 2021-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0052_auto_20210503_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='postpaid_commision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999999, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='prepaid_commision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999999999, null=True),
        ),
    ]
