# Generated by Django 3.1.4 on 2021-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0053_auto_20210503_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('Register', 'Register'), ('Approved', 'Approved'), ('Verified', 'Verified'), ('Draft', 'Draft'), ('Drop', 'Drop')], default='Register', max_length=100, null=True),
        ),
    ]
