# Generated by Django 3.1.4 on 2021-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0054_auto_20210514_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Verified', 'Verified'), ('Draft', 'Draft'), ('Drop', 'Drop')], default='Pending', max_length=100, null=True),
        ),
    ]
