# Generated by Django 3.1.4 on 2021-06-02 16:28

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0055_auto_20210602_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='aadhaar_docs',
            new_name='adhaar_card',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='banking_passbook_docs',
            new_name='cancelled_cheque',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='cancelled_cheque_docs',
            new_name='drug_license',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='drug_docs',
            new_name='gst_certificate',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='fssai_docs',
            new_name='other_license',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='address_1',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='gstin_docs',
            new_name='trade_license',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pan_docs',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='postpaid_commision',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='prepaid_commision',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='scale_docs',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='state',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='trade_docs',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='type_of_seller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='udhyaam_docs',
        ),
        migrations.AlterField(
            model_name='seller',
            name='pan_card',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
    ]
