# Generated by Django 3.1.4 on 2021-06-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0057_seller_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
