# Generated by Django 3.1.4 on 2021-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0058_auto_20210602_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Draft', 'Draft'), ('Drop', 'Drop')], default='Pending', max_length=100, null=True),
        ),
    ]
