# Generated by Django 3.1.4 on 2021-06-03 17:39

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0059_auto_20210603_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='approved_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='cluster',
            field=models.CharField(choices=[('South', 'South'), ('North', 'North'), ('East', 'East'), ('West', 'West')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='order_type',
            field=models.CharField(choices=[('Postpaid', 'Postpaid'), ('Prepaid', 'Prepaid'), ('Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='postpaid_commision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='prepaid_commision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_logo',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_story',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer'), ('Reseller', 'Reseller')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='status_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='verified_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Draft', 'Draft'), ('Declined', 'Declined')], default='Pending', max_length=100, null=True),
        ),
    ]
