# Generated by Django 3.1.4 on 2021-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0060_auto_20210603_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='cluster',
            field=models.CharField(blank=True, choices=[('South', 'South'), ('North', 'North'), ('East', 'East'), ('West', 'West')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Postpaid', 'Postpaid'), ('Prepaid', 'Prepaid'), ('Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='postpaid_commision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='prepaid_commision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_story',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer'), ('Reseller', 'Reseller')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
