# Generated by Django 3.1.4 on 2021-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0061_auto_20210603_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
