# Generated by Django 3.1.3 on 2021-09-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0069_auto_20210603_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('10.00am -  11.00 am', '10.00am -  11.00 am'), ('4.00pm -  5.00 pm', '4.00pm -  5.00 pm'), ('7.00pm - 8.00 pm', '7.00pm -  8.00 pm')], max_length=100, null=True),
        ),
    ]
