# Generated by Django 3.1.3 on 2021-09-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0070_auto_20210904_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
