# Generated by Django 3.1.3 on 2021-09-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0071_auto_20210904_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_verification', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'Approved')], default='Pending', max_length=100, null=True)),
                ('acct_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
