# Generated by Django 3.1.3 on 2021-09-04 23:47

from django.db import migrations, models
import django.db.models.deletion
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0072_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDC_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(default='Pending', max_length=100, null=True)),
                ('tax_rate', models.IntegerField()),
                ('ifsc', models.CharField(blank=True, max_length=100, null=True)),
                ('document', django_base64field.fields.Base64Field(blank=True, default='', max_length=999999999999, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
