# Generated by Django 3.1.3 on 2021-09-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0073_ldc_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldc_details',
            name='validity_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ldc_details',
            name='validity_to',
            field=models.DateField(null=True),
        ),
    ]
