# Generated by Django 3.1.3 on 2021-09-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0074_auto_20210904_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldc_details',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
