# Generated by Django 3.1.3 on 2021-09-05 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0075_ldc_details_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldc_details',
            name='certificate_no',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='seller_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
