# Generated by Django 3.1.3 on 2021-09-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0076_auto_20210905_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'Approved')], default='Pending', max_length=100, null=True)),
                ('credits', models.IntegerField(null=True)),
                ('debits', models.IntegerField(null=True)),
                ('net_amount', models.FloatField(null=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.bank_details')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
