# Generated by Django 3.1.3 on 2021-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0077_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='description',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
