# Generated by Django 3.1.3 on 2021-08-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_myorder_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
