# Generated by Django 3.1.3 on 2021-09-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0017_auto_20210605_1309'),
        ('order', '0006_returnorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer'),
        ),
    ]
