# Generated by Django 3.1.3 on 2021-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210902_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='return_id',
            field=models.IntegerField(default='10000'),
        ),
        migrations.DeleteModel(
            name='returnorder',
        ),
    ]
