# Generated by Django 3.1.3 on 2021-09-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210902_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='con_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='myorder',
            name='pick_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
