# Generated by Django 3.1.3 on 2021-09-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210902_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='boxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myorder',
            name='order_weight',
            field=models.FloatField(null=True),
        ),
    ]
