# Generated by Django 3.1.3 on 2021-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_myorder_weight_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
