# Generated by Django 3.1.3 on 2021-09-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20210903_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
