# Generated by Django 3.1.3 on 2021-09-04 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210903_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='delivery_date',
        ),
    ]
