# Generated by Django 3.1.3 on 2021-09-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_remove_myorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
