# Generated by Django 3.1.3 on 2021-09-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0082_auto_20210905_2236'),
        ('order', '0016_myorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Postpaid', 'Postpaid'), ('Prepaid', 'Prepaid'), ('Both', 'Both')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('credits', models.IntegerField(null=True)),
                ('debits', models.IntegerField(null=True)),
                ('net_amount', models.FloatField(null=True)),
                ('transaction_date', models.DateField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.myorder')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
